# Generated by Django 3.0.7 on 2020-07-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteStar', models.BooleanField(default=False)),
                ('noteStyle', models.CharField(blank=True, max_length=200, null=True)),
                ('noteBold', models.BooleanField(default=False)),
                ('noteItalic', models.BooleanField(default=False)),
                ('noteUnderline', models.BooleanField(default=False)),
                ('noteTextColor', models.CharField(blank=True, max_length=200, null=True)),
                ('noteBackgroundColor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
