# Generated by Django 3.0.7 on 2020-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_notemodel_notevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='noteCreationDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notemodel',
            name='noteCreationTime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
