# Generated by Django 3.0.7 on 2020-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_auto_20200709_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='noteStrikeThrough',
            field=models.BooleanField(default=False),
        ),
    ]
